public class Gen1 extends Dex{

    public void pokemonsNaLista() {
        pokemonArrayList.add(new Pokemon("Bulbasaur", "Macho/Fêmea", 0.7, 6.9, 1, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.MONSTRO.getGrupo(), Habilidades.OVERGROW.getHabilidade(), Habilidades.CHLOROPHYLL.getHabilidade(), "Ivysaur", "Venusaur"));
        pokemonArrayList.add(new Pokemon("Ivysaur", "Macho/Fêmea", 1.0, 13.0, 2, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.MONSTRO.getGrupo(), Habilidades.OVERGROW.getHabilidade(), Habilidades.CHLOROPHYLL.getHabilidade(), "Venusaur", null));
        pokemonArrayList.add(new Pokemon("Venusaur", "Macho/Fêmea", 2.0, 100.0, 3, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.MONSTRO.getGrupo(), Habilidades.OVERGROW.getHabilidade(), Habilidades.CHLOROPHYLL.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Charmander", "Macho/Fêmea", 0.6, 8.5, 4, Tipos.FOGO.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.DRAGAO.getGrupo(), Habilidades.BLAZE.getHabilidade(), Habilidades.SOLAR_POWER.getHabilidade(), "Charmeleon", "Charizard"));
        pokemonArrayList.add(new Pokemon("Charmeleon", "Macho/Fêmea", 1.1, 19.0, 5, Tipos.FOGO.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.DRAGAO.getGrupo(), Habilidades.BLAZE.getHabilidade(), Habilidades.SOLAR_POWER.getHabilidade(), "Charizard", null));
        pokemonArrayList.add(new Pokemon("Charizard", "Macho/Fêmea", 1.7, 90.5, 6, Tipos.FOGO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.DRAGAO.getGrupo(), Habilidades.BLAZE.getHabilidade(), Habilidades.SOLAR_POWER.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Squirtle", "Macho/Fêmea", 0.5, 9.0, 7, Tipos.AGUA.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.TORRENT.getHabilidade(), Habilidades.RAIN_DISH.getHabilidade(), "Wartortle", "Blastoise"));
        pokemonArrayList.add(new Pokemon("Wartortle", "Macho/Fêmea", 1.0, 22.5, 8, Tipos.AGUA.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.TORRENT.getHabilidade(), Habilidades.RAIN_DISH.getHabilidade(), "Blastoise", null));
        pokemonArrayList.add(new Pokemon("Blastoise", "Macho/Fêmea", 1.6, 85.5, 9, Tipos.AGUA.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.TORRENT.getHabilidade(), Habilidades.RAIN_DISH.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Caterpie", "Macho/Fêmea", 0.3, 2.9, 10, Tipos.INSETO.getTipo(), null, GrupoDeOvos.INSETO.getGrupo(), null, Habilidades.SHIELD_DUST.getHabilidade(), Habilidades.RUN_AWAY.getHabilidade(), "Metapod", "Butterfree"));
        pokemonArrayList.add(new Pokemon("Metapod", "Macho/Fêmea", 0.7, 9.9, 11, Tipos.INSETO.getTipo(), null, GrupoDeOvos.INSETO.getGrupo(), null, Habilidades.SHED_SKIN.getHabilidade(), null, "Butterfree", null));
        pokemonArrayList.add(new Pokemon("Butterfree", "Macho/Fêmea", 1.1, 32.0, 12, Tipos.INSETO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.INSETO.getGrupo(), null, Habilidades.COMPOUND_EYES.getHabilidade(), Habilidades.TINTED_LENS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Weedle", "Macho/Fêmea", 0.3, 3.2, 13, Tipos.INSETO.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.INSETO.getGrupo(), null, Habilidades.SHIELD_DUST.getHabilidade(), Habilidades.RUN_AWAY.getHabilidade(), "Kakuna", "Beedrill"));
        pokemonArrayList.add(new Pokemon("Kakuna", "Macho/Fêmea", 0.6, 10.0, 14, Tipos.INSETO.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.INSETO.getGrupo(), null, Habilidades.SHED_SKIN.getHabilidade(), null, "Beedrill", null));
        pokemonArrayList.add(new Pokemon("Beedrill", "Macho/Fêmea", 1.0, 29.5, 15, Tipos.INSETO.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.INSETO.getGrupo(), null, Habilidades.SWARM.getHabilidade(), Habilidades.SNIPER.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Pidgey", "Macho/Fêmea", 0.3, 1.8, 16, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.KEEN_EYE.getHabilidade(), Habilidades.TANGLED_FEET.getHabilidade(), "Pidgeotto", "Pidgeot"));
        pokemonArrayList.add(new Pokemon("Pidgeotto", "Macho/Fêmea", 1.1, 30.0, 17, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.KEEN_EYE.getHabilidade(), Habilidades.TANGLED_FEET.getHabilidade(), "Pidgeot", null));
        pokemonArrayList.add(new Pokemon("Pidgeot", "Macho/Fêmea", 1.5, 39.5, 18, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.KEEN_EYE.getHabilidade(), Habilidades.TANGLED_FEET.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Rattata", "Macho/Fêmea", 0.3, 3.5, 19, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.RUN_AWAY.getHabilidade(), Habilidades.GUTS.getHabilidade(), "Raticate", null));
        pokemonArrayList.add(new Pokemon("Raticate", "Macho/Fêmea", 0.7, 18.5, 20, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.RUN_AWAY.getHabilidade(), Habilidades.GUTS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Spearow", "Macho/Fêmea", 0.3, 2.0, 21, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.KEEN_EYE.getHabilidade(), null, "Fearow", null));
        pokemonArrayList.add(new Pokemon("Fearow", "Macho/Fêmea", 1.2, 38.0, 22, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.KEEN_EYE.getHabilidade(), null, null, null));
        pokemonArrayList.add(new Pokemon("Ekans", "Macho/Fêmea", 2.0, 6.9, 23, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.INTIMIDATE.getHabilidade(), Habilidades.SHED_SKIN.getHabilidade(), "Arbok", null));
        pokemonArrayList.add(new Pokemon("Arbok", "Macho/Fêmea", 3.5, 65.0, 24, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.INTIMIDATE.getHabilidade(), Habilidades.SHED_SKIN.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Pikachu", "Macho/Fêmea", 0.4, 6.0, 25, Tipos.ELETRICO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.STATIC.getHabilidade(), Habilidades.LIGHTNING_ROD.getHabilidade(), "Raichu", null));
        pokemonArrayList.add(new Pokemon("Raichu", "Macho/Fêmea", 0.8, 30.0, 26, Tipos.ELETRICO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.STATIC.getHabilidade(), Habilidades.LIGHTNING_ROD.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Sandshrew", "Macho/Fêmea", 0.6, 12.0, 27, Tipos.TERRESTRE.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.SAND_VEIL.getHabilidade(), Habilidades.SAND_RUSH.getHabilidade(), "Sandslash", null));
        pokemonArrayList.add(new Pokemon("Sandslash", "Macho/Fêmea", 1.0, 29.5, 28, Tipos.TERRESTRE.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.SAND_VEIL.getHabilidade(), Habilidades.SAND_RUSH.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Nidoran♀", "Fêmea", 0.4, 7.0, 29, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.POISON_POINT.getHabilidade(), Habilidades.RIVALRY.getHabilidade(), "Nidorina", "Nidoqueen"));
        pokemonArrayList.add(new Pokemon("Nidorina", "Fêmea", 0.8, 20.0, 30, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.POISON_POINT.getHabilidade(), Habilidades.RIVALRY.getHabilidade(), "Nidoqueen", null));
        pokemonArrayList.add(new Pokemon("Nidoqueen", "Fêmea", 1.3, 60.0, 31, Tipos.VENENOSO.getTipo(), Tipos.TERRESTRE.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.POISON_POINT.getHabilidade(), Habilidades.SHEER_FORCE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Nidoran♂", "Macho", 0.5, 9.0, 32, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.POISON_POINT.getHabilidade(), Habilidades.RIVALRY.getHabilidade(), "Nidorino", "Nidoking"));
        pokemonArrayList.add(new Pokemon("Nidorino", "Macho", 0.9, 19.5, 33, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.POISON_POINT.getHabilidade(), Habilidades.RIVALRY.getHabilidade(), "Nidoking", null));
        pokemonArrayList.add(new Pokemon("Nidoking", "Macho", 1.4, 62.0, 34, Tipos.VENENOSO.getTipo(), Tipos.TERRESTRE.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.POISON_POINT.getHabilidade(), Habilidades.SHEER_FORCE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Clefairy", "Macho/Fêmea", 0.6, 7.5, 35, Tipos.FADA.getTipo(), null, GrupoDeOvos.FADA.getGrupo(), null, Habilidades.CUTE_CHARM.getHabilidade(), Habilidades.MAGIC_GUARD.getHabilidade(), "Clefable", null));
        pokemonArrayList.add(new Pokemon("Clefable", "Macho/Fêmea", 1.3, 40.0, 36, Tipos.FADA.getTipo(), null, GrupoDeOvos.FADA.getGrupo(), null, Habilidades.CUTE_CHARM.getHabilidade(), Habilidades.MAGIC_GUARD.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Vulpix", "Macho/Fêmea", 0.6, 9.9, 37, Tipos.FOGO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.FLASH_FIRE.getHabilidade(), Habilidades.DROUGHT.getHabilidade(), "Ninetales", null));
        pokemonArrayList.add(new Pokemon("Ninetales", "Macho/Fêmea", 1.1, 19.9, 38, Tipos.FOGO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.FLASH_FIRE.getHabilidade(), Habilidades.DROUGHT.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Jigglypuff", "Macho/Fêmea", 0.5, 5.5, 39, Tipos.NORMAL.getTipo(), Tipos.FADA.getTipo(), GrupoDeOvos.FADA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CUTE_CHARM.getHabilidade(), Habilidades.FRIEND_GUARD.getHabilidade(), "Wigglytuff", null));
        pokemonArrayList.add(new Pokemon("Wigglytuff", "Macho/Fêmea", 1.0, 12.0, 40, Tipos.NORMAL.getTipo(), Tipos.FADA.getTipo(), GrupoDeOvos.FADA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CUTE_CHARM.getHabilidade(), Habilidades.FRIEND_GUARD.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Zubat", "Macho/Fêmea", 0.8, 7.5, 41, Tipos.VENENOSO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.VOADOR.getGrupo(), GrupoDeOvos.INDETERMINADO.getGrupo(), Habilidades.INNER_FOCUS.getHabilidade(), Habilidades.INFILTRATOR.getHabilidade(), "Golbat", "Crobat"));
        pokemonArrayList.add(new Pokemon("Golbat", "Macho/Fêmea", 1.6, 55.0, 42, Tipos.VENENOSO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.VOADOR.getGrupo(), GrupoDeOvos.INDETERMINADO.getGrupo(), Habilidades.INNER_FOCUS.getHabilidade(), Habilidades.INFILTRATOR.getHabilidade(), "Crobat", null));
        pokemonArrayList.add(new Pokemon("Oddish", "Macho/Fêmea", 0.5, 5.4, 43, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), Habilidades.RUN_AWAY.getHabilidade(), "Gloom", "Vileplume"));
        pokemonArrayList.add(new Pokemon("Gloom", "Macho/Fêmea", 0.8, 8.6, 44, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), Habilidades.STENCH.getHabilidade(), "Vileplume", "Bellossom"));
        pokemonArrayList.add(new Pokemon("Vileplume", "Macho/Fêmea", 1.2, 18.6, 45, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), Habilidades.EFFECT_SPORE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Paras", "Macho/Fêmea", 0.3, 5.4, 46, Tipos.INSETO.getTipo(), Tipos.GRAMA.getTipo(), GrupoDeOvos.INSETO.getGrupo(), GrupoDeOvos.GRAMA.getGrupo(), Habilidades.EFFECT_SPORE.getHabilidade(), Habilidades.DRY_SKIN.getHabilidade(), "Parasect", null));
        pokemonArrayList.add(new Pokemon("Parasect", "Macho/Fêmea", 1.0, 29.5, 47, Tipos.INSETO.getTipo(), Tipos.GRAMA.getTipo(), GrupoDeOvos.INSETO.getGrupo(), GrupoDeOvos.GRAMA.getGrupo(), Habilidades.EFFECT_SPORE.getHabilidade(), Habilidades.DRY_SKIN.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Venonat", "Macho/Fêmea", 1.0, 30.0, 48, Tipos.INSETO.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.INSETO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.COMPOUND_EYES.getHabilidade(), Habilidades.TINTED_LENS.getHabilidade(), "Venomoth", null));
        pokemonArrayList.add(new Pokemon("Venomoth", "Macho/Fêmea", 1.5, 12.5, 49, Tipos.INSETO.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.INSETO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.SHIELD_DUST.getHabilidade(), Habilidades.TINTED_LENS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Diglett", "Macho/Fêmea", 0.2, 0.8, 50, Tipos.TERRESTRE.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.SAND_VEIL.getHabilidade(), Habilidades.ARENA_TRAP.getHabilidade(), "Dugtrio", null));
        pokemonArrayList.add(new Pokemon("Dugtrio", "Macho/Fêmea", 0.7, 33.3, 51, Tipos.TERRESTRE.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.SAND_VEIL.getHabilidade(), Habilidades.ARENA_TRAP.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Meowth", "Macho/Fêmea", 0.4, 4.2, 52, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.PICKUP.getHabilidade(), Habilidades.TECHNICIAN.getHabilidade(), "Persian", null));
        pokemonArrayList.add(new Pokemon("Persian", "Macho/Fêmea", 1.0, 32.0, 53, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.LIMBER.getHabilidade(), Habilidades.TECHNICIAN.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Psyduck", "Macho/Fêmea", 0.8, 19.6, 54, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.DAMP.getHabilidade(), Habilidades.CLOUD_NINE.getHabilidade(), "Golduck", null));
        pokemonArrayList.add(new Pokemon("Golduck", "Macho/Fêmea", 1.7, 76.6, 55, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.DAMP.getHabilidade(), Habilidades.CLOUD_NINE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Mankey", "Macho/Fêmea", 0.5, 28.0, 56, Tipos.LUTADOR.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.HUMANOIDE.getGrupo(), Habilidades.VITAL_SPIRIT.getHabilidade(), Habilidades.ANGER_POINT.getHabilidade(), "Primeape", null));
        pokemonArrayList.add(new Pokemon("Primeape", "Macho/Fêmea", 1.0, 32.0, 57, Tipos.LUTADOR.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.HUMANOIDE.getGrupo(), Habilidades.VITAL_SPIRIT.getHabilidade(), Habilidades.ANGER_POINT.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Growlithe", "Macho/Fêmea", 0.7, 19.0, 58, Tipos.FOGO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.MONSTRO.getGrupo(), Habilidades.INTIMIDATE.getHabilidade(), Habilidades.FLASH_FIRE.getHabilidade(), "Arcanine", null));
        pokemonArrayList.add(new Pokemon("Arcanine", "Macho/Fêmea", 1.9, 155.0, 59, Tipos.FOGO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.MONSTRO.getGrupo(), Habilidades.INTIMIDATE.getHabilidade(), Habilidades.FLASH_FIRE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Poliwag", "Macho/Fêmea", 0.6, 12.4, 60, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_1.getGrupo(), null, Habilidades.WATER_ABSORB.getHabilidade(), Habilidades.DAMP.getHabilidade(), "Poliwhirl", "Poliwrath"));
        pokemonArrayList.add(new Pokemon("Poliwhirl", "Macho/Fêmea", 1.0, 20.0, 61, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_1.getGrupo(), null, Habilidades.WATER_ABSORB.getHabilidade(), Habilidades.DAMP.getHabilidade(), "Poliwrath", "Politoed"));
        pokemonArrayList.add(new Pokemon("Poliwrath", "Macho/Fêmea", 1.3, 54.0, 62, Tipos.AGUA.getTipo(), Tipos.LUTADOR.getTipo(), GrupoDeOvos.AGUA_1.getGrupo(), null, Habilidades.WATER_ABSORB.getHabilidade(), Habilidades.DAMP.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Abra", "Macho/Fêmea", 0.9, 19.5, 63, Tipos.PSIQUICO.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.SYNCHRONIZE.getHabilidade(), Habilidades.INNER_FOCUS.getHabilidade(), "Kadabra", "Alakazam"));
        pokemonArrayList.add(new Pokemon("Kadabra", "Macho/Fêmea", 1.3, 56.5, 64, Tipos.PSIQUICO.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.SYNCHRONIZE.getHabilidade(), Habilidades.INNER_FOCUS.getHabilidade(), "Alakazam", null));
        pokemonArrayList.add(new Pokemon("Alakazam", "Macho/Fêmea", 1.5, 48.0, 65, Tipos.PSIQUICO.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.SYNCHRONIZE.getHabilidade(), Habilidades.INNER_FOCUS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Machop", "Macho/Fêmea", 0.8, 19.5, 66, Tipos.LUTADOR.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.GUTS.getHabilidade(), Habilidades.NO_GUARD.getHabilidade(), "Machoke", "Machamp"));
        pokemonArrayList.add(new Pokemon("Machoke", "Macho/Fêmea", 1.5, 70.5, 67, Tipos.LUTADOR.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.GUTS.getHabilidade(), Habilidades.NO_GUARD.getHabilidade(), "Machamp", null));
        pokemonArrayList.add(new Pokemon("Machamp", "Macho/Fêmea", 1.6, 130.0, 68, Tipos.LUTADOR.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.GUTS.getHabilidade(), Habilidades.NO_GUARD.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Bellsprout", "Macho/Fêmea", 0.7, 4.0, 69, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), Habilidades.GLUTTONY.getHabilidade(), "Weepinbell", "Victreebel"));
        pokemonArrayList.add(new Pokemon("Weepinbell", "Macho/Fêmea", 1.0, 6.4, 70, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), Habilidades.GLUTTONY.getHabilidade(), "Victreebel", null));
        pokemonArrayList.add(new Pokemon("Victreebel", "Macho/Fêmea", 1.7, 15.5, 71, Tipos.GRAMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), Habilidades.GLUTTONY.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Tentacool", "Macho/Fêmea", 0.9, 45.5, 72, Tipos.AGUA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.AGUA_3.getGrupo(), null, Habilidades.CLEAR_BODY.getHabilidade(), Habilidades.LIQUID_OOZE.getHabilidade(), "Tentacruel", null));
        pokemonArrayList.add(new Pokemon("Tentacruel", "Macho/Fêmea", 1.6, 55.0, 73, Tipos.AGUA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.AGUA_3.getGrupo(), null, Habilidades.CLEAR_BODY.getHabilidade(), Habilidades.LIQUID_OOZE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Geodude", "Macho/Fêmea", 0.4, 20.0, 74, Tipos.PEDRA.getTipo(), Tipos.TERRESTRE.getTipo(), GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.ROCK_HEAD.getHabilidade(), Habilidades.STURDY.getHabilidade(), "Graveler", "Golem"));
        pokemonArrayList.add(new Pokemon("Graveler", "Macho/Fêmea", 1.0, 105.0, 75, Tipos.PEDRA.getTipo(), Tipos.TERRESTRE.getTipo(), GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.ROCK_HEAD.getHabilidade(), Habilidades.STURDY.getHabilidade(), "Golem", null));
        pokemonArrayList.add(new Pokemon("Golem", "Macho/Fêmea", 1.4, 300.0, 76, Tipos.PEDRA.getTipo(), Tipos.TERRESTRE.getTipo(), GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.ROCK_HEAD.getHabilidade(), Habilidades.STURDY.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Ponyta", "Macho/Fêmea", 1.0, 30.0, 77, Tipos.FOGO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.RUN_AWAY.getHabilidade(), Habilidades.FLAME_BODY.getHabilidade(), "Rapidash", null));
        pokemonArrayList.add(new Pokemon("Rapidash", "Macho/Fêmea", 1.7, 95.0, 78, Tipos.FOGO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.RUN_AWAY.getHabilidade(), Habilidades.FLAME_BODY.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Slowpoke", "Macho/Fêmea", 1.2, 36.0, 79, Tipos.AGUA.getTipo(), Tipos.PSIQUICO.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.OBLIVIOUS.getHabilidade(), Habilidades.OWN_TEMPO.getHabilidade(), "Slowbro", "Slowking"));
        pokemonArrayList.add(new Pokemon("Slowbro", "Macho/Fêmea", 1.6, 78.5, 80, Tipos.AGUA.getTipo(), Tipos.PSIQUICO.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.OBLIVIOUS.getHabilidade(), Habilidades.OWN_TEMPO.getHabilidade(), "Slowking", null));
        pokemonArrayList.add(new Pokemon("Magnemite", "Sem Gênero", 0.3, 6.0, 81, Tipos.ELETRICO.getTipo(), Tipos.METAL.getTipo(), GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.MAGNET_PULL.getHabilidade(), Habilidades.STURDY.getHabilidade(), "Magneton", "Magnezone"));
        pokemonArrayList.add(new Pokemon("Magneton", "Sem Gênero", 1.0, 60.0, 82, Tipos.ELETRICO.getTipo(), Tipos.METAL.getTipo(), GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.MAGNET_PULL.getHabilidade(), Habilidades.STURDY.getHabilidade(), "Magnezone", null));
        pokemonArrayList.add(new Pokemon("Farfetch'd", "Macho/Fêmea", 0.8, 15.0, 83, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.KEEN_EYE.getHabilidade(), Habilidades.INNER_FOCUS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Doduo", "Macho/Fêmea", 1.4, 39.2, 84, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.RUN_AWAY.getHabilidade(), Habilidades.EARLY_BIRD.getHabilidade(), "Dodrio", null));
        pokemonArrayList.add(new Pokemon("Dodrio", "Macho/Fêmea", 1.8, 85.2, 85, Tipos.NORMAL.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.CAMPO.getGrupo(), GrupoDeOvos.VOADOR.getGrupo(), Habilidades.RUN_AWAY.getHabilidade(), Habilidades.EARLY_BIRD.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Seel", "Macho/Fêmea", 1.1, 90.0, 86, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_1.getGrupo(), null, Habilidades.THICK_FAT.getHabilidade(), Habilidades.HYDRATION.getHabilidade(), "Dewgong", null));
        pokemonArrayList.add(new Pokemon("Dewgong", "Macho/Fêmea", 1.7, 120.0, 87, Tipos.AGUA.getTipo(), Tipos.GELO.getTipo(), GrupoDeOvos.AGUA_1.getGrupo(), null, Habilidades.THICK_FAT.getHabilidade(), Habilidades.HYDRATION.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Grimer", "Macho/Fêmea", 0.9, 30.0, 88, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.AMORFO.getGrupo(), null, Habilidades.STENCH.getHabilidade(), Habilidades.STICKY_HOLD.getHabilidade(), "Muk", null));
        pokemonArrayList.add(new Pokemon("Muk", "Macho/Fêmea", 1.2, 30.0, 89, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.AMORFO.getGrupo(), null, Habilidades.STENCH.getHabilidade(), Habilidades.STICKY_HOLD.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Shellder", "Macho/Fêmea", 0.3, 4.0, 90, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_3.getGrupo(), null, Habilidades.SHELL_ARMOR.getHabilidade(), Habilidades.SKILL_LINK.getHabilidade(), "Cloyster", null));
        pokemonArrayList.add(new Pokemon("Cloyster", "Macho/Fêmea", 1.5, 132.5, 91, Tipos.AGUA.getTipo(), Tipos.GELO.getTipo(), GrupoDeOvos.AGUA_3.getGrupo(), null, Habilidades.SHELL_ARMOR.getHabilidade(), Habilidades.SKILL_LINK.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Gastly", "Macho/Fêmea", 1.3, 0.1, 92, Tipos.FANTASMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.AMORFO.getGrupo(), null, Habilidades.LEVITATE.getHabilidade(), null, "Haunter", "Gengar"));
        pokemonArrayList.add(new Pokemon("Haunter", "Macho/Fêmea", 1.6, 0.1, 93, Tipos.FANTASMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.AMORFO.getGrupo(), null, Habilidades.LEVITATE.getHabilidade(), null, "Gengar", null));
        pokemonArrayList.add(new Pokemon("Gengar", "Macho/Fêmea", 1.5, 40.5, 94, Tipos.FANTASMA.getTipo(), Tipos.VENENOSO.getTipo(), GrupoDeOvos.AMORFO.getGrupo(), null, Habilidades.LEVITATE.getHabilidade(), null, null, null));
        pokemonArrayList.add(new Pokemon("Onix", "Macho/Fêmea", 8.8, 210.0, 95, Tipos.PEDRA.getTipo(), Tipos.TERRESTRE.getTipo(), GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.ROCK_HEAD.getHabilidade(), Habilidades.STURDY.getHabilidade(), "Steelix", null));
        pokemonArrayList.add(new Pokemon("Drowzee", "Macho/Fêmea", 1.0, 32.4, 96, Tipos.PSIQUICO.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.INSOMNIA.getHabilidade(), Habilidades.FOREWARN.getHabilidade(), "Hypno", null));
        pokemonArrayList.add(new Pokemon("Hypno", "Macho/Fêmea", 1.6, 75.6, 97, Tipos.PSIQUICO.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.INSOMNIA.getHabilidade(), Habilidades.FOREWARN.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Krabby", "Macho/Fêmea", 0.4, 6.5, 98, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_3.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.HYPER_CUTTER.getHabilidade(), Habilidades.SHELL_ARMOR.getHabilidade(), "Kingler", null));
        pokemonArrayList.add(new Pokemon("Kingler", "Macho/Fêmea", 1.3, 60.0, 99, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_3.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.HYPER_CUTTER.getHabilidade(), Habilidades.SHELL_ARMOR.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Voltorb", "Sem Gênero", 0.5, 10.4, 100, Tipos.ELETRICO.getTipo(), null, GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.SOUNDPROOF.getHabilidade(), Habilidades.STATIC.getHabilidade(), "Electrode", null));
        pokemonArrayList.add(new Pokemon("Electrode", "Sem Gênero", 1.2, 66.6, 101, Tipos.ELETRICO.getTipo(), null, GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.SOUNDPROOF.getHabilidade(), Habilidades.STATIC.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Exeggcute", "Macho/Fêmea", 0.4, 2.5, 102, Tipos.GRAMA.getTipo(), Tipos.PSIQUICO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), null, "Exeggutor", null));
        pokemonArrayList.add(new Pokemon("Exeggutor", "Macho/Fêmea", 2.0, 120.0, 103, Tipos.GRAMA.getTipo(), Tipos.PSIQUICO.getTipo(), GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), null, null, null));
        pokemonArrayList.add(new Pokemon("Cubone", "Macho/Fêmea", 0.4, 6.5, 104, Tipos.TERRESTRE.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.ROCK_HEAD.getHabilidade(), Habilidades.LIGHTNING_ROD.getHabilidade(), "Marowak", null));
        pokemonArrayList.add(new Pokemon("Marowak", "Macho/Fêmea", 1.0, 45.0, 105, Tipos.TERRESTRE.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.ROCK_HEAD.getHabilidade(), Habilidades.LIGHTNING_ROD.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Hitmonlee", "Macho", 1.5, 49.8, 106, Tipos.LUTADOR.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.LIMBER.getHabilidade(), Habilidades.RECKLESS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Hitmonchan", "Macho", 1.4, 50.2, 107, Tipos.LUTADOR.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.KEEN_EYE.getHabilidade(), Habilidades.IRON_FIST.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Lickitung", "Macho/Fêmea", 1.2, 65.5, 108, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.OWN_TEMPO.getHabilidade(), Habilidades.OBLIVIOUS.getHabilidade(), "Lickilicky", null));
        pokemonArrayList.add(new Pokemon("Koffing", "Macho/Fêmea", 0.6, 1.0, 109, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.AMORFO.getGrupo(), null, Habilidades.LEVITATE.getHabilidade(), Habilidades.NEUTRALIZING_GAS.getHabilidade(), "Weezing", null));
        pokemonArrayList.add(new Pokemon("Weezing", "Macho/Fêmea", 1.2, 9.5, 110, Tipos.VENENOSO.getTipo(), null, GrupoDeOvos.AMORFO.getGrupo(), null, Habilidades.LEVITATE.getHabilidade(), Habilidades.NEUTRALIZING_GAS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Rhyhorn", "Macho/Fêmea", 1.0, 115.0, 111, Tipos.TERRESTRE.getTipo(), Tipos.PEDRA.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.LIGHTNING_ROD.getHabilidade(), Habilidades.ROCK_HEAD.getHabilidade(), "Rhydon", "Rhyperior"));
        pokemonArrayList.add(new Pokemon("Rhydon", "Macho/Fêmea", 1.9, 120.0, 112, Tipos.TERRESTRE.getTipo(), Tipos.PEDRA.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.LIGHTNING_ROD.getHabilidade(), Habilidades.ROCK_HEAD.getHabilidade(), "Rhyperior", null));
        pokemonArrayList.add(new Pokemon("Chansey", "Fêmea", 1.1, 34.6, 113, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.FADA.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.NATURAL_CURE.getHabilidade(), Habilidades.SERENE_GRACE.getHabilidade(), "Blissey", null));
        pokemonArrayList.add(new Pokemon("Tangela", "Macho/Fêmea", 1.0, 35.0, 114, Tipos.GRAMA.getTipo(), null, GrupoDeOvos.GRAMA.getGrupo(), GrupoDeOvos.MONSTRO.getGrupo(), Habilidades.CHLOROPHYLL.getHabilidade(), Habilidades.LEAF_GUARD.getHabilidade(), "Tangrowth", null));
        pokemonArrayList.add(new Pokemon("Kangaskhan", "Fêmea", 2.2, 80.0, 115, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.EARLY_BIRD.getHabilidade(), Habilidades.SCRAPPY.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Horsea", "Macho/Fêmea", 0.4, 8.0, 116, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.DRAGAO.getGrupo(), Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.SNIPER.getHabilidade(), "Seadra", "Kingdra"));
        pokemonArrayList.add(new Pokemon("Seadra", "Macho/Fêmea", 1.2, 25.0, 117, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.DRAGAO.getGrupo(), Habilidades.POISON_POINT.getHabilidade(), Habilidades.SNIPER.getHabilidade(), "Kingdra", null));
        pokemonArrayList.add(new Pokemon("Goldeen", "Macho/Fêmea", 0.6, 15.0, 118, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_2.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.WATER_VEIL.getHabilidade(), "Seaking", null));
        pokemonArrayList.add(new Pokemon("Seaking", "Macho/Fêmea", 1.3, 39.0, 119, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_2.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.WATER_VEIL.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Staryu", "Sem Gênero", 0.8, 34.5, 120, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_3.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.ILLUMINATE.getHabilidade(), Habilidades.NATURAL_CURE.getHabilidade(), "Starmie", null));
        pokemonArrayList.add(new Pokemon("Starmie", "Sem Gênero", 1.1, 80.0, 121, Tipos.AGUA.getTipo(), Tipos.PSIQUICO.getTipo(), GrupoDeOvos.AGUA_3.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.ILLUMINATE.getHabilidade(), Habilidades.NATURAL_CURE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Mr. Mime", "Macho/Fêmea", 1.3, 54.5, 122, Tipos.PSIQUICO.getTipo(), Tipos.FADA.getTipo(), GrupoDeOvos.HUMANOIDE.getGrupo(), GrupoDeOvos.FADA.getGrupo(), Habilidades.SOUNDPROOF.getHabilidade(), Habilidades.FILTER.getHabilidade(), "Mr. Rime", null));
        pokemonArrayList.add(new Pokemon("Scyther", "Macho/Fêmea", 1.5, 56.0, 123, Tipos.INSETO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.INSETO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.SWARM.getHabilidade(), Habilidades.TECHNICIAN.getHabilidade(), "Scizor", null));
        pokemonArrayList.add(new Pokemon("Jynx", "Fêmea", 1.4, 40.6, 124, Tipos.GELO.getTipo(), Tipos.PSIQUICO.getTipo(), GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.OBLIVIOUS.getHabilidade(), Habilidades.FOREWARN.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Electabuzz", "Macho/Fêmea", 1.1, 30.0, 125, Tipos.ELETRICO.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.STATIC.getHabilidade(), Habilidades.VITAL_SPIRIT.getHabilidade(), "Electivire", null));
        pokemonArrayList.add(new Pokemon("Magmar", "Macho/Fêmea", 1.3, 44.5, 126, Tipos.FOGO.getTipo(), null, GrupoDeOvos.HUMANOIDE.getGrupo(), null, Habilidades.FLAME_BODY.getHabilidade(), Habilidades.VITAL_SPIRIT.getHabilidade(), "Magmortar", null));
        pokemonArrayList.add(new Pokemon("Pinsir", "Macho/Fêmea", 1.5, 55.0, 127, Tipos.INSETO.getTipo(), null, GrupoDeOvos.INSETO.getGrupo(), null, Habilidades.HYPER_CUTTER.getHabilidade(), Habilidades.MOXIE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Tauros", "Macho", 1.4, 88.4, 128, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.INTIMIDATE.getHabilidade(), Habilidades.ANGER_POINT.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Magikarp", "Macho/Fêmea", 0.9, 10.0, 129, Tipos.AGUA.getTipo(), null, GrupoDeOvos.AGUA_2.getGrupo(), null, Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.RATTLED.getHabilidade(), "Gyarados", null));
        pokemonArrayList.add(new Pokemon("Gyarados", "Macho/Fêmea", 6.5, 235.0, 130, Tipos.AGUA.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.AGUA_2.getGrupo(), null, Habilidades.INTIMIDATE.getHabilidade(), Habilidades.MOXIE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Lapras", "Macho/Fêmea", 2.5, 220.0, 131, Tipos.AGUA.getTipo(), Tipos.GELO.getTipo(), GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.WATER_ABSORB.getHabilidade(), Habilidades.SHELL_ARMOR.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Ditto", "Sem Gênero", 0.3, 4.0, 132, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.DITTO.getGrupo(), null, Habilidades.LIMBER.getHabilidade(), Habilidades.IMPOSTER.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Eevee", "Macho/Fêmea", 0.3, 6.5, 133, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.RUN_AWAY.getHabilidade(), Habilidades.ADAPTABILITY.getHabilidade(), "Vaporeon", "Jolteon"));
        pokemonArrayList.add(new Pokemon("Vaporeon", "Macho/Fêmea", 1.0, 29.0, 134, Tipos.AGUA.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.WATER_ABSORB.getHabilidade(), Habilidades.HYDRATION.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Jolteon", "Macho/Fêmea", 0.8, 24.5, 135, Tipos.ELETRICO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.VOLT_ABSORB.getHabilidade(), Habilidades.QUICK_FEET.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Flareon", "Macho/Fêmea", 0.9, 25.0, 136, Tipos.FOGO.getTipo(), null, GrupoDeOvos.CAMPO.getGrupo(), null, Habilidades.FLASH_FIRE.getHabilidade(), Habilidades.GUTS.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Porygon", "Sem Gênero", 0.8, 36.5, 137, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.MINERAL.getGrupo(), null, Habilidades.TRACE.getHabilidade(), Habilidades.DOWNLOAD.getHabilidade(), "Porygon2", "Porygon-Z"));
        pokemonArrayList.add(new Pokemon("Omanyte", "Macho/Fêmea", 0.4, 7.5, 138, Tipos.PEDRA.getTipo(), Tipos.AGUA.getTipo(), GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.SHELL_ARMOR.getHabilidade(), "Omastar", null));
        pokemonArrayList.add(new Pokemon("Omastar", "Macho/Fêmea", 1.0, 35.0, 139, Tipos.PEDRA.getTipo(), Tipos.AGUA.getTipo(), GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.SHELL_ARMOR.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Kabuto", "Macho/Fêmea", 0.5, 11.5, 140, Tipos.PEDRA.getTipo(), Tipos.AGUA.getTipo(), GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.BATTLE_ARMOR.getHabilidade(), "Kabutops", null));
        pokemonArrayList.add(new Pokemon("Kabutops", "Macho/Fêmea", 1.3, 40.5, 141, Tipos.PEDRA.getTipo(), Tipos.AGUA.getTipo(), GrupoDeOvos.AGUA_1.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.SWIFT_SWIM.getHabilidade(), Habilidades.BATTLE_ARMOR.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Aerodactyl", "Macho/Fêmea", 1.8, 59.0, 142, Tipos.PEDRA.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.VOADOR.getGrupo(), GrupoDeOvos.MINERAL.getGrupo(), Habilidades.ROCK_HEAD.getHabilidade(), Habilidades.PRESSURE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Snorlax", "Macho/Fêmea", 2.1, 460.0, 143, Tipos.NORMAL.getTipo(), null, GrupoDeOvos.MONSTRO.getGrupo(), GrupoDeOvos.CAMPO.getGrupo(), Habilidades.IMMUNITY.getHabilidade(), Habilidades.THICK_FAT.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Articuno", "Sem Gênero", 1.7, 55.4, 144, Tipos.GELO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.INDETERMINADO.getGrupo(), null, Habilidades.PRESSURE.getHabilidade(), Habilidades.SNOW_CLOAK.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Zapdos", "Sem Gênero", 1.6, 52.6, 145, Tipos.ELETRICO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.INDETERMINADO.getGrupo(), null, Habilidades.PRESSURE.getHabilidade(), Habilidades.STATIC.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Moltres", "Sem Gênero", 2.0, 60.0, 146, Tipos.FOGO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.INDETERMINADO.getGrupo(), null, Habilidades.PRESSURE.getHabilidade(), Habilidades.FLAME_BODY.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Dratini", "Macho/Fêmea", 1.8, 3.3, 147, Tipos.DRAGAO.getTipo(), null, GrupoDeOvos.DRAGAO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.SHED_SKIN.getHabilidade(), Habilidades.MARVEL_SCALE.getHabilidade(), "Dragonair", "Dragonite"));
        pokemonArrayList.add(new Pokemon("Dragonair", "Macho/Fêmea", 4.0, 16.5, 148, Tipos.DRAGAO.getTipo(), null, GrupoDeOvos.DRAGAO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.SHED_SKIN.getHabilidade(), Habilidades.MARVEL_SCALE.getHabilidade(), "Dragonite", null));
        pokemonArrayList.add(new Pokemon("Dragonite", "Macho/Fêmea", 2.2, 210.0, 149, Tipos.DRAGAO.getTipo(), Tipos.VOADOR.getTipo(), GrupoDeOvos.DRAGAO.getGrupo(), GrupoDeOvos.AGUA_1.getGrupo(), Habilidades.INNER_FOCUS.getHabilidade(), Habilidades.MULTISCALE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Mewtwo", "Sem Gênero", 2.0, 122.0, 150, Tipos.PSIQUICO.getTipo(), null, GrupoDeOvos.INDETERMINADO.getGrupo(), null, Habilidades.PRESSURE.getHabilidade(), Habilidades.UNNERVE.getHabilidade(), null, null));
        pokemonArrayList.add(new Pokemon("Mew", "Sem Gênero", 0.4, 4.0, 151, Tipos.PSIQUICO.getTipo(), null, GrupoDeOvos.INDETERMINADO.getGrupo(), null, Habilidades.SYNCHRONIZE.getHabilidade(), null, null,  null));
    }

    @Override
    public void mostrarPokemons() {
        super.mostrarPokemons();
    }

    @Override
    public Pokemon buscarPokemonNumero(int numero) {
         return super.buscarPokemonNumero(numero);
    }

    @Override
    public Pokemon buscarPokemon(String nome) {
         return super.buscarPokemon(nome);
    }

}
