public enum Habilidades {
    ADAPTABILITY("Adaptability"),
    AERILATE("Aerilate"),
    AFTERMATH("Aftermath"),
    AIR_LOCK("Air Lock"),
    ANALYTIC("Analytic"),
    ANGER_POINT("Anger Point"),
    ANGER_SHELL("Anger Shell"),
    ANTICIPATION("Anticipation"),
    ARENA_TRAP("Arena Trap"),
    ARMOR_TAIL("Armor Tail"),
    AROMA_VEIL("Aroma Veil"),
    AS_ONE("As One"),
    AURA_BREAK("Aura Break"),
    BAD_DREAMS("Bad Dreams"),
    BALL_FETCH("Ball Fetch"),
    BATTERY("Battery"),
    BATTLE_ARMOR("Battle Armor"),
    BATTLE_BOND("Battle Bond"),
    BEADS_OF_RUIN("Beads of Ruin"),
    BEAST_BOOST("Beast Boost"),
    BERSERK("Berserk"),
    BIG_PECKS("Big Pecks"),
    BLAZE("Blaze"),
    BULLETPROOF("Bulletproof"),
    CHEEK_POUCH("Cheek Pouch"),
    CHILLING_NEIGH("Chilling Neigh"),
    CHLOROPHYLL("Chlorophyll"),
    CLEAR_BODY("Clear Body"),
    CLOUD_NINE("Cloud Nine"),
    COLOR_CHANGE("Color Change"),
    COMATOSE("Comatose"),
    COMMANDER("Commander"),
    COMPETITIVE("Competitive"),
    COMPOUND_EYES("Compound Eyes"),
    CONTRARY("Contrary"),
    CORROSION("Corrosion"),
    COSTAR("Costar"),
    COTTON_DOWN("Cotton Down"),
    CUD_CHEW("Cud Chew"),
    CURIOUS_MEDICINE("Curious Medicine"),
    CURSED_BODY("Cursed Body"),
    CUTE_CHARM("Cute Charm"),
    DAMP("Damp"),
    DANCER("Dancer"),
    DARK_AURA("Dark Aura"),
    DAUNTLESS_SHIELD("Dauntless Shield"),
    DAZZLING("Dazzling"),
    DEFEATIST("Defeatist"),
    DEFIANT("Defiant"),
    DELTA_STREAM("Delta Stream"),
    DESOLATE_LAND("Desolate Land"),
    DISGUISE("Disguise"),
    DOWNLOAD("Download"),
    DRAGON_S_MAW("Dragon's Maw"),
    DRIZZLE("Drizzle"),
    DROUGHT("Drought"),
    DRY_SKIN("Dry Skin"),
    EARLY_BIRD("Early Bird"),
    EARTH_EATER("Earth Eater"),
    EFFECT_SPORE("Effect Spore"),
    ELECTRIC_SURGE("Electric Surge"),
    ELECTROMORPHOSIS("Electromorphosis"),
    EMBODY_ASPECT("Embody Aspect"),
    EMERGENCY_EXIT("Emergency Exit"),
    FAIRY_AURA("Fairy Aura"),
    FILTER("Filter"),
    FLAME_BODY("Flame Body"),
    FLARE_BOOST("Flare Boost"),
    FLASH_FIRE("Flash Fire"),
    FLOWER_GIFT("Flower Gift"),
    FLOWER_VEIL("Flower Veil"),
    FLUFFY("Fluffy"),
    FORECAST("Forecast"),
    FOREWARN("Forewarn"),
    FRIEND_GUARD("Friend Guard"),
    FRISK("Frisk"),
    FULL_METAL_BODY("Full Metal Body"),
    FUR_COAT("Fur Coat"),
    GALE_WINGS("Gale Wings"),
    GALVANIZE("Galvanize"),
    GLAUTENY("Glauteny"),
    GLUTTONY("Gluttony"),
    GOOD_AS_GOLD("Good as Gold"),
    GOOEY("Gooey"),
    GORILLA_TACTICS("Gorilla Tactics"),
    GRASS_PELT("Grass Pelt"),
    GRASSY_SURGE("Grassy Surge"),
    GRIM_NEIGH("Grim Neigh"),
    GUARD_DOG("Guard Dog"),
    GULP_MISSILE("Gulp Missile"),
    GUTS("Guts"),
    HADRON_ENGINE("Hadron Engine"),
    HARVEST("Harvest"),
    HEALER("Healer"),
    HEATPROOF("Heatproof"),
    HEAVY_METAL("Heavy Metal"),
    HONEY_GATHER("Honey Gather"),
    HOSPITALITY("Hospitality"),
    HUGE_POWER("Huge Power"),
    HUNGER_SWITCH("Hunger Switch"),
    HUSTLE("Hustle"),
    HYDRATION("Hydration"),
    HYPER_CUTTER("Hyper Cutter"),
    ICE_BODY("Ice Body"),
    ICE_FACE("Ice Face"),
    ICE_SCALES("Ice Scales"),
    ILLUMINATE("Illuminate"),
    ILLUSION("Illusion"),
    IMMUNITY("Immunity"),
    IMPOSTER("Imposter"),
    INFILTRATOR("Infiltrator"),
    INNARDS_OUT("Innards Out"),
    INNER_FOCUS("Inner Focus"),
    INSOMNIA("Insomnia"),
    INTIMIDATE("Intimidate"),
    INTREPID_SWORD("Intrepid Sword"),
    IRON_BARS("Iron Barbs"),
    IRON_FIST("Iron Fist"),
    JUSTIFIED("Justified"),
    KEEN_EYE("Keen Eye"),
    KLUTZ("Klutz"),
    LEAF_GUARD("Leaf Guard"),
    LEVITATE("Levitate"),
    LIBERO("Libero"),
    LIGHT_METAL("Light Metal"),
    LIGHTNING_ROD("Lightning Rod"),
    LIMBER("Limber"),
    LINGERING_AROMA("Lingering Aroma"),
    LIQUID_OOZE("Liquid Ooze"),
    LIQUID_VOICE("Liquid Voice"),
    LONG_REACH("Long Reach"),
    MAGIC_BOUNCE("Magic Bounce"),
    MAGIC_GUARD("Magic Guard"),
    MAGICIAN("Magician"),
    MAGMA_ARMOR("Magma Armor"),
    MAGNET_PULL("Magnet Pull"),
    MARVEL_SCALE("Marvel Scale"),
    MEGA_LAUNCHER("Mega Launcher"),
    MERCILESS("Merciless"),
    MIMICRY("Mimicry"),
    MIND_S_EYE("Mind's Eye"),
    MINUS("Minus"),
    MIRROR_ARMOR("Mirror Armor"),
    MISTY_SURGE("Misty Surge"),
    MOLD_BREAKER("Mold Breaker"),
    MOODY("Moody"),
    MOTOR_DRIVE("Motor Drive"),
    MOXIE("Moxie"),
    MULTISCALE("Multiscale"),
    MULTITYPE("Multitype"),
    MUMMY("Mummy"),
    MYCELIUM_MIGHT("Mycelium Might"),
    NATURAL_CURE("Natural Cure"),
    NEUROFORCE("Neuroforce"),
    NEUTRALIZING_GAS("Neutralizing Gas"),
    NO_GUARD("No Guard"),
    NORMALIZE("Normalize"),
    OBLIVIOUS("Oblivious"),
    OPPORTUNIST("Opportunist"),
    ORICHALCUM_PULSE("Orichalcum Pulse"),
    OVERCOAT("Overcoat"),
    OVERGROW("Overgrow"),
    OWN_TEMPO("Own Tempo"),
    PARENTAL_BOND("Parental Bond"),
    PASTEL_VEIL("Pastel Veil"),
    PERISH_BODY("Perish Body"),
    PICKPOCKET("Pickpocket"),
    PICKUP("Pickup"),
    PIXILATE("Pixilate"),
    PLUS("Plus"),
    POISON_HEAL("Poison Heal"),
    POISON_POINT("Poison Point"),
    POISON_PUPPETEER("Poison Puppeteer"),
    POISON_TOUCH("Poison Touch"),
    POWER_CONSTRUCT("Power Construct"),
    POWER_OF_ALCHEMY("Power of Alchemy"),
    POWER_SPOT("Power Spot"),
    PRANKSTER("Prankster"),
    PRESSURE("Pressure"),
    PRIMORDIAL_SEA("Primordial Sea"),
    PRISM_ARMOR("Prism Armor"),
    PROPPELLER_TAIL("Propeller Tail"),
    PROTEAN("Protean"),
    PROTOSYNTHESIS("Protosynthesis"),
    PSYCHIC_SURGE("Psychic Surge"),
    PUNK_ROCK("Punk Rock"),
    PURE_POWER("Pure Power"),
    PURIFYING_SALT("Purifying Salt"),
    QUARK_DRIVE("Quark Drive"),
    QUEENLY_MAJESTY("Queenly Majesty"),
    QUICK_DRAW("Quick Draw"),
    QUICK_FEET("Quick Feet"),
    RAIN_DISH("Rain Dish"),
    RATTLED("Rattled"),
    RECEIVER("Receiver"),
    RECKLESS("Reckless"),
    REFLECT("Reflect"),
    REGNERATOR("Regenerator"),
    RIPEN("Ripen"),
    RIVALRY("Rivalry"),
    RKS_SYSTEM("RKS System"),
    ROCK_HEAD("Rock Head"),
    ROCKY_PAYLOAD("Rocky Payload"),
    ROUGH_SKIN("Rough Skin"),
    RUN_AWAY("Run Away"),
    SAND_FORCE("Sand Force"),
    SAND_RUSH("Sand Rush"),
    SAND_SPIT("Sand Spit"),
    SAND_STREAM("Sand Stream"),
    SAND_VEIL("Sand Veil"),
    SAP_SIPPER("Sap Sipper"),
    SCHOOLING("Schooling"),
    SCRAPPY("Scrappy"),
    SCREEN_CLEANER("Screen Cleaner"),
    SEED_SOWER("Seed Sower"),
    SERENE_GRACE("Serene Grace"),
    SHADOW_SHIELD("Shadow Shield"),
    SHADOW_TAG("Shadow Tag"),
    SHARPEN("Sharpness"),
    SHED_SKIN("Shed Skin"),
    SHEER_FORCE("Sheer Force"),
    SHELL_ARMOR("Shell Armor"),
    SHIELD_DUST("Shield Dust"),
    SHOPPING_BAG("Shopping Bag"),
    SHUCKLE("Shuckle"),
    SIMPLE("Simple"),
    SKILL_LINK("Skill Link"),
    SKY_DROP("Sky Drop"),
    SLUSH_RUSH("Slush Rush"),
    SNIPER("Sniper"),
    SNOW_CLOAK("Snow Cloak"),
    SNOW_WARNING("Snow Warning"),
    SOAK("Soak"),
    SOLAR_POWER("Solar Power"),
    SOLID_ROCK("Solid Rock"),
    SOUNDPROOF("Soundproof"),
    SOUL_HEART("Soul Heart"),
    SOUL_WINGS("Soul Wings"),
    SPEED_BOOST("Speed Boost"),
    SPONGY_BODY("Spongy Body"),
    SPOTTER("Spotter"),
    STALWART("Stalwart"),
    STANCE_CHANGE("Stance Change"),
    STATIC("Static"),
    STEADFAST("Steadfast"),
    STEELWORKER("Steelworker"),
    STENCH("Stench"),
    STICKY_HOLD("Sticky Hold"),
    STORM_DRAIN("Storm Drain"),
    STURDY("Sturdy"),
    SUCTION_CUPS("Suction Cups"),
    SUPER_LUCK("Super Luck"),
    SWARM("Swarm"),
    SWIFT_SWIM("Swift Swim"),
    SYNERGY("Synergy"),
    SYNCHRONIZE("Synchronize"),
    TANGLED_FEET("Tangled Feet"),
    TANGLED_TAIL("Tangled Tail"),
    TANGLED_WINGS("Tangled Wings"),
    TERRA_VOLT("Terra Volt"),
    TINTED_LENS("Tinted Lens"),
    TECHNICIAN("Technician"),
    THICK_FAT("Thick Fat"),
    TORRENT("Torrent"),
    TOXIC_BOOST("Toxic Boost"),
    TOXIC_PRESERVE("Toxic Preserve"),
    TRACE("trace"),
    TRANSLUCENT("Translucent"),
    TRICKSTER("Trickster"),
    TYPHLOSION("Typhlosion"),
    URSHIFU("Urshifu"),
    UNNERVE("Unnerve"),
    UNSEEN_FIST("Unseen Fist"),
    UNYIELDING("Unyielding"),
    URBANIZE("Urbanize"),
    VANITY("Vanity"),
    VEIL_OF_GRACE("Veil of Grace"),
    VITAL_SPIRIT("Vital Spirit"),
    VOLT_ABSORB("Volt absorb"),
    WATER_ABSORB("Water Absorb"),
    WATER_BUBBLE("Water Bubble"),
    WATER_COMBAT("Water Combat"),
    WATER_VEIL("Water Veil"),
    WEATHER_BOOST("Weather Boost"),
    WELL_PRESERVED("Well Preserved"),
    WICKED_BLOW("Wicked Blow"),
    WINDFALL("Windfall"),
    WINTER_WINGS("Winter Wings"),
    WIRELESS("Wireless"),
    WONDER_GUARD("Wonder Guard"),
    WOUND_HEAL("Wound Heal"),
    YAWNING_TALISMAN("Yawning Talisman"),
    ZEN_MODE("Zen Mode");

    private final String habilidade;

    Habilidades(String habilidade) {
        this.habilidade = habilidade;
    }

    public String getHabilidade() {
        return habilidade;
    }
}

